### ISSUE TITLE
Document Markdown support

### ISSUE THREAD

**Issue by halindrome** [w3c/respec-docs#45]
We don't have any information about this!

**Comment by travisleithead** [comment]
Does is support:
- auto paragraph generation?
- auto bulleted and number lists
- dl/dt/dd using `:` `::`
- backtic-for-code elements

I'm curious because I've been working lately in Bikeshed and have developed a love for these minimalist syntaxes, as I'm sure others have. Would love to hear/see what ReSpec can do!

**Comment by travisleithead** [comment]
I just tested, and indeed it does! You folks have done (and continue to do) great work. Keep it up!

**Comment by marcoscaceres** [comment]
@travisleithead, glad to hear it :) Working to improve documentation.
